apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.data.name }}-http
  labels:
    {{- range $k, $v := .Values.data.selector }}
      {{ $k }}: {{ $v }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.data.service.http.port }}
      protocol: TCP
      name: {{ .Values.data.service.http.name }}
  selector:
    {{- range $k, $v := .Values.data.selector }}
      {{ $k }}: {{ $v }}
    {{- end }}
