apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.data.name }}-transport
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.data.service.transport.port }}
      protocol: TCP
      name: {{ .Values.data.service.transport.name }}
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
