apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.data.name }}-http
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.data.service.http.port }}
      protocol: TCP
      name: {{ .Values.data.service.http.name }}
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
