apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.master.name }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.master.service.port }}
      protocol: TCP
      name: {{ .Values.master.service.name }}
  selector:
    {{- include "elasticsearch.selectorLabels" . | nindent 4 }}
